//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPDX.CodeAnalysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPDX.CodeAnalysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;SPDX-License-Identifier:&apos; is required header comment on all C# code files..
        /// </summary>
        internal static string SPDX_1000_AnalyzerDescription {
            get {
                return ResourceManager.GetString("SPDX_1000_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header comment including &apos;SPDX-License-Identifier:&apos; is required.
        /// </summary>
        internal static string SPDX_1000_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("SPDX_1000_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;SPDX-License-Identifier:&apos; is required header comment on all C# code files.
        /// </summary>
        internal static string SPDX_1000_AnalyzerTitle {
            get {
                return ResourceManager.GetString("SPDX_1000_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        internal static string SPDX_1001_AnalyzerDescription {
            get {
                return ResourceManager.GetString("SPDX_1001_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        internal static string SPDX_1001_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("SPDX_1001_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        internal static string SPDX_1001_AnalyzerTitle {
            get {
                return ResourceManager.GetString("SPDX_1001_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;SPDX-CopyrightText:&apos; is required header comment on all C# code files..
        /// </summary>
        internal static string SPDX_1002_AnalyzerDescription {
            get {
                return ResourceManager.GetString("SPDX_1002_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header comment including &apos;SPDX-CopyrightText:&apos; is required.
        /// </summary>
        internal static string SPDX_1002_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("SPDX_1002_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;SPDX-CopyrightText:&apos; is required header comment on all C# code files.
        /// </summary>
        internal static string SPDX_1002_AnalyzerTitle {
            get {
                return ResourceManager.GetString("SPDX_1002_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        internal static string SPDX_1003_AnalyzerDescription {
            get {
                return ResourceManager.GetString("SPDX_1003_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        internal static string SPDX_1003_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("SPDX_1003_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        internal static string SPDX_1003_AnalyzerTitle {
            get {
                return ResourceManager.GetString("SPDX_1003_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        internal static string SPDX_1004_AnalyzerDescription {
            get {
                return ResourceManager.GetString("SPDX_1004_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        internal static string SPDX_1004_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("SPDX_1004_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        internal static string SPDX_1004_AnalyzerTitle {
            get {
                return ResourceManager.GetString("SPDX_1004_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License text block is required header comment on all C# code files..
        /// </summary>
        internal static string SPDX_1005_AnalyzerDescription {
            get {
                return ResourceManager.GetString("SPDX_1005_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header comment including license text is required.
        /// </summary>
        internal static string SPDX_1005_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("SPDX_1005_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License text block is required header comment on all C# code files.
        /// </summary>
        internal static string SPDX_1005_AnalyzerTitle {
            get {
                return ResourceManager.GetString("SPDX_1005_AnalyzerTitle", resourceCulture);
            }
        }
    }
}
