name: Renovate

on:
  workflow_dispatch:       # allows manual runs
  schedule:
    - cron: "0 3 * * 1"    # 3 AM Monday UTC (same as ASF-friendly schedule)

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.11
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: NightOwl888/SPDX.CodeAnalysis
          LOG_LEVEL: debug
