name: SPDX.CodeAnalysis

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        shell: pwsh
        run: |
          $nugetOut = "$(Join-Path $PWD 'dist/nuget')"
          dotnet build -c Release --no-restore -p:PackageOutputPath=$nugetOut

      - name: Publish test assemblies
        shell: pwsh
        run: |
          $testsOut = "$(Join-Path $PWD 'dist/tests')"
          New-Item -ItemType Directory -Force -Path $testsOut | Out-Null
          Get-ChildItem -Recurse -Filter *.csproj -Path test | ForEach-Object {
              $projName = $_.BaseName
              $outDir = Join-Path $testsOut $projName
              dotnet publish $_.FullName -c Release --no-restore -o $outDir
          }

      - name: Collect NuGet packages
        shell: pwsh
        run: |
          $nugetOut = "$(Join-Path $PWD 'dist/nuget')"
          New-Item -ItemType Directory -Force -Path $nugetOut | Out-Null
          Get-ChildItem -Recurse -Filter *.nupkg | Copy-Item -Destination $nugetOut -Force

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: dist/nuget

      - name: Upload test assemblies
        uses: actions/upload-artifact@v4
        with:
          name: test-assemblies
          path: dist/tests
