name: Test Powershell Scripts

on:
  workflow_dispatch:
  push:
  pull_request:
  
jobs:
  pester:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Restore Powershell Dependencies
        shell: pwsh
        run: ./.build/Ensure-Powershell-Dependencies.ps1

      - name: Run Pester
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: Invoke-Pester -Output Detailed -CI -Path .
